name: scoped_bloc_example
description: Scoped BLoC example
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Annotation & Code-generation
  meta: ^1.7.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # State manager & Inversion of Control
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

  # Storage and SQL
  shared_preferences: ^2.0.5

  # Utility & Helpers
  l: ^3.0.1
  async: ^2.6.1
  collection: ^1.15.0

  # Transformers
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  build_web_compilers: ^3.2.1
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pubspec_generator: ^3.0.1
  flutter_gen_runner: ^5.3.2
  args: ^2.0.0
  pub_semver: ^2.1.0

flutter:
  uses-material-design: true

# Flutter assets codegen
flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
